# Generated by Django 4.0 on 2024-01-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0004_imageprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageProfile',
        ),
    ]
