# Generated by Django 4.0 on 2024-01-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('specialization', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
    ]
