# Generated by Django 4.0 on 2023-12-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, verbose_name='Бренд авто')),
                ('model', models.CharField(max_length=20, verbose_name='Модель авто')),
                ('horsepower', models.IntegerField(verbose_name='Лошадиные силы')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
            ],
        ),
    ]
