# Generated by Django 4.0 on 2023-12-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='название ингредиента')),
                ('ingredient_amount', models.FloatField(verbose_name='грамм')),
            ],
            options={
                'verbose_name': 'ингредиент',
                'verbose_name_plural': 'ингредиенты',
                'db_table': 'ingredient',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='название блюда')),
                ('price', models.FloatField(verbose_name='цена блюда')),
                ('ingredient', models.ManyToManyField(related_name='ingredients', to='app_meal.Ingredient', verbose_name='ингредиенты')),
            ],
            options={
                'verbose_name': 'блюдо',
                'verbose_name_plural': 'блюда',
                'db_table': 'meal',
            },
        ),
    ]
