# Generated by Django 4.0 on 2023-12-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20, verbose_name='Модель наушников')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет')),
                ('charge', models.CharField(max_length=20, verbose_name='Время работы')),
            ],
        ),
    ]
