# Generated by Django 4.0 on 2023-12-07 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя автора')),
                ('birth_date', models.DateField(verbose_name='Дата роджения')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название книги')),
                ('publication_date', models.DateField(verbose_name='Дата публикации')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_writers.writer', verbose_name='Автор')),
            ],
        ),
    ]
