# Generated by Django 4.0 on 2023-12-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_writers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.TextField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='birth_date',
            field=models.TextField(verbose_name='Дата роджения'),
        ),
    ]
