# Generated by Django 4.0 on 2023-12-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_writers', '0002_alter_book_publication_date_alter_writer_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
